WIP: yosys-uhdm: use uhdm-plugin
hdl/conda-eda pull request #118
Opened 2021-07-19 07:19 UTC by kamilrakoczy

This PR replaces building uhdm as a part of yosys frontend to external plugin.

2021-08-16 11:20 UTC, kamilrakoczy commented
It was necessary to add building ``libunwind`` and ``gperftools`` packages to get rid if ``conda-forge`` channel. ``conda-forge`` channel was creating conflicts when we don't want to use it, but we still want to install ``yosys-uhdm`` package (e.g. ``fpga-tool-perf``).

2021-08-17 15:00 UTC, ajelinski requested changes
The most important change is adding `run_exports` to `libunwind`.

BTW. I know some of the `yosys-uhdm` changes are outside the scope of this PR but let's fix it. Some of these only make the recipe unnecessarily complicated so it'll make the recipe easier to modify and maintain.

2021-08-18 06:16 UTC, kamilrakoczy commented on misc/gperftools/meta.yaml
> +    - {{ pin_compatible('libunwind', max_pin='x.x') }}  # [linux]
Fixed

2021-08-18 06:16 UTC, kamilrakoczy commented on misc/libunwind/meta.yaml
> +# Use `conda-build-prepare` before building for a better version string.
Removed

2021-08-18 06:16 UTC, kamilrakoczy commented on misc/libunwind/meta.yaml
> +    - lib64.patch
Ok, removed

2021-08-18 06:16 UTC, kamilrakoczy commented on misc/libunwind/meta.yaml
> +build:
Fixed

2021-08-18 06:20 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
> +	cd ..
Ok, I left it as it is for now.

2021-08-18 06:20 UTC, kamilrakoczy commented on syn/yosys-uhdm/meta.yaml
> +    - libunwind
Done

2021-08-18 06:20 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
> +INSTALL_PATH=${PWD}/image
True, I removed ``INSTALL_PATH``

2021-08-18 06:20 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
> +cd yosys && make ENABLE_READLINE=0 CONFIG=conda-linux PROGRAM_PREFIX=uhdm- PREFIX=$INSTALL_PATH install -j$(nproc) && cd ..
Fixed

2021-08-18 06:21 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
> +export PATH=$INSTALL_PATH/bin:${PATH}
Done

2021-08-18 06:21 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
>  mkdir -p "$PREFIX/"
Done

2021-08-18 06:21 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
> +UHDM_INSTALL_DIR=$INSTALL_PATH make -C $PWD/yosys-symbiflow-plugins/ install -j$(nproc)
Fixed

2021-08-18 06:21 UTC, kamilrakoczy commented on syn/yosys-uhdm/meta.yaml
> +    - libunwind
Fixed

2021-08-18 06:21 UTC, kamilrakoczy commented on syn/yosys-uhdm/build.sh
Done

2021-08-18 13:47 UTC, ajelinski approved these changes

2021-08-18 13:52 UTC, merged