Drop antmicro-yosys
hdl/conda-eda pull request #137
Opened 2021-09-27 08:53 UTC by tgorochowik

This fork is not maintained anymore. All the relevant patches are merged
upstream.

2021-09-27 09:00 UTC, PiotrZierhoffer requested changes
The change is required for the master-package job

2021-09-27 09:00 UTC, PiotrZierhoffer commented on .github/workflows/build-packages.yml
> -
Please adjust NUM_OF_JOBS in this file

2021-09-27 09:08 UTC, tgorochowik commented on .github/workflows/build-packages.yml
> -
Sure, adjusted

2021-09-28 14:31 UTC, PiotrZierhoffer approved these changes

2021-09-28 14:32 UTC, merged